CREATE DATABASE IF NOT EXISTS TurboMailDB;
USE TurboMailDB;

CREATE TABLE IF NOT EXISTS users (
  Email VARCHAR(100) NOT NULL,
  Firstname VARCHAR(100) NOT NULL,
  Lastname VARCHAR(100) NOT NULL,
  Passwd VARCHAR(255) NOT NULL,
  PRIMARY KEY (Email)
);