CREATE DATABASE IF NOT EXISTS TurboMailDB;
USE TurboMailDB;

CREATE TABLE IF NOT EXISTS users (
  idUser BIGINT NOT NULL AUTO_INCREMENT,
  Email VARCHAR(100) NOT NULL UNIQUE,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  PRIMARY KEY (idUser)
);